CREATE TABLE rooms (
    room_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    host_id BIGINT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    code VARCHAR(255) NOT NULL
);

CREATE TABLE teams (
    team_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    room_id BIGINT NOT NULL REFERENCES rooms(room_id)
);

CREATE TABLE players (
    player_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    room_id BIGINT NOT NULL REFERENCES rooms(room_id),
    team_id BIGINT NULL REFERENCES teams(team_id),
    username VARCHAR(255) NOT NULL
);

ALTER TABLE rooms ADD CONSTRAINT host_id FOREIGN KEY (host_id) REFERENCES players(player_id);

CREATE TABLE games (
    game_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    room_id BIGINT NOT NULL REFERENCES rooms(room_id),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    ended_at TIMESTAMP WITH TIME ZONE NULL
);

CREATE TABLE rounds (
    round_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    game_id BIGINT NOT NULL REFERENCES games(game_id),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    ended_at TIMESTAMP WITH TIME ZONE NULL
);

CREATE TABLE questions (
    question_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type VARCHAR(255) NOT NULL,
    text TEXT NOT NULL,
    media_url TEXT NULL,
    options TEXT[] NULL,
    correct_answers TEXT[] NULL
);

CREATE TABLE round_questions (
    round_id BIGINT NOT NULL REFERENCES rounds(round_id),
    question_id BIGINT NOT NULL REFERENCES questions(question_id),
    PRIMARY KEY (round_id, question_id)
);

CREATE TABLE answers (
    answer_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    round_id BIGINT NOT NULL REFERENCES rounds(round_id),
    question_id BIGINT NOT NULL REFERENCES questions(question_id),
    player_id BIGINT NOT NULL REFERENCES players(player_id),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    answer TEXT NOT NULL,
    correct BOOLEAN NULL
);
